name: Java CI with Maven

on:
  push:
    branches: ["dang"]
  pull_request:
    branches: ["dang"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build and Test with Maven
        run: mvn -B -e clean test --file CarRental2/pom.xml # Xóa -X để giảm log, giữ -e cho stack trace
      - name: Upload Surefire Reports
        if: always() # Upload luôn để xem báo cáo, kể cả thành công
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: CarRental2/target/surefire-reports/
          retention-days: 5 # Giữ artifact 5 ngày
